name: Deploy
on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

env:
  GITHUB_ACTIONS: true # For tools that might adjust output for GHA
  FORCE_COLOR: 1
  GRADLE_OPTS: -Dorg.gradle.daemon=false # Ensure Gradle daemon is not used
  LC_ALL: en_US.UTF-8 # Recommended for Fastlane
  LANG: en_US.UTF-8   # Recommended for Fastlane

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.13.0

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # - name: Download ktlint-compose.jar
    #   run: |
    #     devbox run -- wget https://github.com/mrmans0n/compose-rules/releases/download/v0.4.16/ktlint-compose-0.4.16-all.jar -O ktlint-compose.jar

    # - name: Lint code
    #   run: |
    #     devbox run -- ktlint -R ktlint-compose.jar "app/src/**/*.kt" "app/build.gradle.kts" "build.gradle.kts" "settings.gradle.kts"

    - name: Build project
      run: |
        devbox run -- ./gradlew assembleDebug

    - name: Prepare Keystore and Play Store Service Account
      run: |
        mkdir -p keys
        printf "%s" "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keys/keystore.jks
        printf "%s" "${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}" > keys/play-service-account.json
        ls -l keys
        cat keys/play-service-account.json
        file keys/keystore.jks
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}

    - name: Deploy to Play Store with Fastlane
      run: |
        devbox run -- fastlane playstore
      env:
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
