name: Test
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

env:
  GITHUB_ACTIONS: true # For tools that might adjust output for GHA
  FORCE_COLOR: 1
  GRADLE_OPTS: -Dorg.gradle.daemon=false # Ensure Gradle daemon is not used

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.13.0
      with:
        enable-cache: 'true'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build
      run: |
        devbox run -- just apk

    - name: Test
      run: |
        devbox run -- just test

    - name: Lint
      run: |
        devbox run -- just lint

